Feat: create attendances download route
PalavrasDePaz/backend pull request #127
Opened 2023-11-09 14:57 UTC by Gonzagadavid

# Description 

- create route dowload to attendances;
- add to csv
- return buffer

# Related issue

- part of issue [Create download routes](https://trello.com/c/bJQceH1c/29-create-download-routes)

2023-11-13 01:47 UTC, JVSRamos requested changes
Well Done! I just requested a change on the route documentation, specifying that it returns a stream as an attachment, as tsoa does not generate it automatically in this way.

2023-11-13 01:47 UTC, JVSRamos commented on src/presentation/api/attendances.ts
> +   * Get download all attendances from a specified date (the format of the date parameter is: yyyy-mm-dd)
```suggestion
   * Get download all attendances from a specified date (the format of the date parameter is: yyyy-mm-dd)
   * OBS: This route returns the data as a stream with attachment headers
```

2023-11-13 14:11 UTC, Gonzagadavid commented on src/presentation/api/attendances.ts
> +   * Get download all attendances from a specified date (the format of the date parameter is: yyyy-mm-dd)
done!

2023-11-14 00:53 UTC, JVSRamos approved these changes
Nice!

2023-11-14 01:08 UTC, merged